language: node_js
node_js:
  - "6"
  - "7"
install: "cd packages/react-formctrl && yarn"
before_script: "cd ../../"
script: "npm test && cat ./coverage/lcov.info | ./packages/react-formctrl/node_modules/coveralls/bin/coveralls.js"